sudo: required
services:
  - docker
  
before_install:
    - docker build -t gerioo/react-test -f ./client/Dockerfile.dev ./client

script:
      -  docker run -e CI=true gerioo/react-test npm test    
    
after_success:
  - docker build -t gerioo/multi-client ./client
  - docker build -t gerioo/multi-nginx ./nginx
  - docker build -t gerioo/multi-server ./server
  - docker build -t gerioo/multi-worker ./worker

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push gerioo/multi-client
  - docker push gerioo/multi-nginx
  - docker push gerioo/multi-server
  - docker push gerioo/multi-worker
  
deploy:
  edge: true
  provider: elasticbeanstalk
  region: eu-central-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-central-1-379644753186
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_acess_key: $AWS_SECRET_KEY
        
  
  
